[package]
name = "rust-pomodoro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4"
symlink = "0.1.0"
clap = { version = "3.2.19", features = ["derive"] }

